package com.example.DatingAppProject.domain;

import java.time.LocalDate;

public class User {

    public User(String email, String password, String role, int phone, String firstName, String lastName, String gender,
                LocalDate birthDate) {
        this.email = email;
        this.password = password;
        this.role = role;
        this.phone = phone;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.birthDate = birthDate;
    }

    private int id; // just used to demo retrieval of autogenerated key in UserMapper
    private String email;
    private String password; // Should be hashed and secured
    private String role;
    private int phone;
    private String firstName;
    private String lastName;
    private String gender;
    private LocalDate birthDate;

    public User(String email, String password, String role) {
    }

    public User(String email, String password) {
    }


    public String getEmail() { return email; }

    public void setEmail(String email) { this.email = email; }

    public String getRole() { return role; }

    public void setRole(String role) { this.role = role; }

    public int getPhone() { return phone; }

    public void setPhone(int phone) { this.phone = phone; }

    public String getFirstName() { return firstName; }

    public void setFirstName(String firstName) { this.firstName = firstName; }

    public String getLastName() { return lastName; }

    public void setLastName(String lastName) { this.lastName = lastName; }

    public String getGender() { return gender; }

    public void setGender(String gender) { this.gender = gender; }

    public LocalDate getBirthDate() { return birthDate; }

    public void setBirthDate(LocalDate birthDate) { this.birthDate = birthDate; }

    public int getId() { return id; }

    public void setId(int id) { this.id = id; }
}
